#!/usr/bin/env bash
# Runs `codegen_fk` against every URDF under assets/urdf/, writing generated
# FK code into src/generated/. Continues past failures and reports a summary,
# since not every robot is expected to succeed yet (see codegen_fk.rs's
# hardcoded "base_link" root-link assumption).
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

URDF_DIR="assets/urdf"
OUT_DIR="src/generated"

echo "==> building codegen_fk"
cargo build --bin codegen_fk
BIN="target/debug/codegen_fk"

ok_count=0
fail_count=0
module_names=()

while IFS= read -r -d '' urdf; do
    stem="$(basename "$urdf" .urdf)"
    # Sanitize into a valid Rust module name: lowercase, non-alnum -> '_', collapse/trim underscores.
    name="$(echo "$stem" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/_/g; s/^_+|_+$//g')"
    out="$OUT_DIR/${name}.rs"

    echo "==> $urdf -> $out"
    if "$BIN" "$urdf" "$out"; then
        ok_count=$((ok_count + 1))
        module_names+=("$name")
    else
        echo "    FAILED: $urdf"
        fail_count=$((fail_count + 1))
    fi
done < <(find "$URDF_DIR" -name '*.urdf' -print0 | sort -z)

# Regenerate mod.rs from scratch so it always matches what's actually on disk —
# hand-maintaining `pub mod` lines here just drifts out of sync as robots are added.
mod_rs="$OUT_DIR/mod.rs"
echo "==> regenerating $mod_rs"
{
    echo "// Auto-generated by scripts/codegen_all_urdfs.sh. Do not edit by hand."
    for name in "${module_names[@]}"; do
        echo "pub mod ${name};"
    done
} > "$mod_rs"

echo
echo "==> $ok_count succeeded, $fail_count failed"
[ "$fail_count" -eq 0 ]
